
import { Navigation } from "../../components/Navigation"
import React from "react";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "О нас",
  description: "Generated by create next app",
};


const navItems = [
  { label: 'Contacts', href: '/about/contacts' },
  { label: 'Team', href: '/about/team' },
]


export default function AboutLayout({ children }: { children: React.ReactNode; }) {
  return (
    <>

      <h1 className="text-2xl text-center">About us</h1>

      <div className="header">
        <ul className="flex gap-2">
          <Navigation navLinks={navItems}/>
        </ul>
      </div>

      {children}

    </>
  )
}