import Link from "next/link";
import React from "react";
import type {Metadata} from "next";


export const metadata: Metadata = {
    title: "О нас",
    description: "Generated by create next app",
};
export default function AboutLayout({
                                        children,
                                    }: {
    children: React.ReactNode;
}) {
    return (
        <>
            <h1 className="text-2xl text-center">About us</h1>
            <ul className="flex gap-2">
                <li><Link href="/about/contacts">Contacts</Link></li>
                <li><Link href="/about/team">Team</Link></li>
            </ul>

            {children}
        </>
    )
}